spark:
  master: "k8s://https://kubernetes.default.svc"
  app_name: "RetestReport"
  driver_host: "localhost"
  driver_port: "30011"
  ui_port: "4040"
  executor_instances: 3
  executor_cores: 2
  executor_memory: "4g"
  driver_memory: "4g"
  jars_packages: "io.delta:delta-spark_2.12:3.2.0,org.apache.hadoop:hadoop-aws:3.3.4"
  sql_extensions: "io.delta.sql.DeltaSparkSessionExtension"
  sql_catalog_spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"

s3:
  endpoint: "http://minio.minio.svc:9000"
  access_key: "minio"
  secret_key: "minio123"
  bucket: "data"

app:
  factory: "gumi"
  top_codes:
    - "TOP41"
    - "TOP42"
    - "others"
  model_count: 5
  start_date: "20250705"
  end_date: "20250810"
  start_duration: "2025-07-07 07:00:00"
  end_duration: "2025-08-09 07:00:00"
